/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IBank {
  export type ViewDataStruct = {
    totalClients: BigNumberish;
    aggregateFee: BigNumberish;
  };

  export type ViewDataStructOutput = [
    totalClients: bigint,
    aggregateFee: bigint
  ] & { totalClients: bigint; aggregateFee: bigint };

  export type ViewUserDataStruct = {
    access: boolean;
    collateralBalance: BigNumberish;
  };

  export type ViewUserDataStructOutput = [
    access: boolean,
    collateralBalance: bigint
  ] & { access: boolean; collateralBalance: bigint };
}

export declare namespace Common {
  export type ContributorStruct = {
    durOfChoice: BigNumberish;
    paybackTime: BigNumberish;
    turnStartTime: BigNumberish;
    getFinanceTime: BigNumberish;
    loan: BigNumberish;
    colBals: BigNumberish;
    id: AddressLike;
    sentQuota: boolean;
    interestPaid: BigNumberish;
  };

  export type ContributorStructOutput = [
    durOfChoice: bigint,
    paybackTime: bigint,
    turnStartTime: bigint,
    getFinanceTime: bigint,
    loan: bigint,
    colBals: bigint,
    id: string,
    sentQuota: boolean,
    interestPaid: bigint
  ] & {
    durOfChoice: bigint;
    paybackTime: bigint;
    turnStartTime: bigint;
    getFinanceTime: bigint;
    loan: bigint;
    colBals: bigint;
    id: string;
    sentQuota: boolean;
    interestPaid: bigint;
  };

  export type Payback_BankStruct = {
    user: AddressLike;
    asset: AddressLike;
    debt: BigNumberish;
    attestedInitialBal: BigNumberish;
    allGF: boolean;
    cData: Common.ContributorStruct[];
    isSwapped: boolean;
    defaulted: AddressLike;
    rId: BigNumberish;
    collateralToken: AddressLike;
  };

  export type Payback_BankStructOutput = [
    user: string,
    asset: string,
    debt: bigint,
    attestedInitialBal: bigint,
    allGF: boolean,
    cData: Common.ContributorStructOutput[],
    isSwapped: boolean,
    defaulted: string,
    rId: bigint,
    collateralToken: string
  ] & {
    user: string;
    asset: string;
    debt: bigint;
    attestedInitialBal: bigint;
    allGF: boolean;
    cData: Common.ContributorStructOutput[];
    isSwapped: boolean;
    defaulted: string;
    rId: bigint;
    collateralToken: string;
  };
}

export interface BankInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addUp"
      | "cancel"
      | "feeTo"
      | "getData"
      | "getFinance"
      | "getUserData"
      | "ownershipManager"
      | "payback"
      | "setOwnershipManager"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addUp",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeTo", values?: undefined): string;
  encodeFunctionData(functionFragment: "getData", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFinance",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserData",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownershipManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payback",
    values: [Common.Payback_BankStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwnershipManager",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addUp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFinance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownershipManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payback", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOwnershipManager",
    data: BytesLike
  ): Result;
}

export interface Bank extends BaseContract {
  connect(runner?: ContractRunner | null): Bank;
  waitForDeployment(): Promise<this>;

  interface: BankInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addUp: TypedContractMethod<
    [user: AddressLike, rId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  cancel: TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      unit: BigNumberish,
      rId: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  feeTo: TypedContractMethod<[], [string], "view">;

  getData: TypedContractMethod<[], [IBank.ViewDataStructOutput], "view">;

  getFinance: TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      loan: BigNumberish,
      fee: BigNumberish,
      calculatedCol: BigNumberish,
      rId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getUserData: TypedContractMethod<
    [user: AddressLike, rId: BigNumberish],
    [IBank.ViewUserDataStructOutput],
    "view"
  >;

  ownershipManager: TypedContractMethod<[], [string], "view">;

  payback: TypedContractMethod<
    [_p: Common.Payback_BankStruct],
    [boolean],
    "nonpayable"
  >;

  setOwnershipManager: TypedContractMethod<
    [newManager: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addUp"
  ): TypedContractMethod<
    [user: AddressLike, rId: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      unit: BigNumberish,
      rId: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeTo"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getData"
  ): TypedContractMethod<[], [IBank.ViewDataStructOutput], "view">;
  getFunction(
    nameOrSignature: "getFinance"
  ): TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      loan: BigNumberish,
      fee: BigNumberish,
      calculatedCol: BigNumberish,
      rId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getUserData"
  ): TypedContractMethod<
    [user: AddressLike, rId: BigNumberish],
    [IBank.ViewUserDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownershipManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payback"
  ): TypedContractMethod<
    [_p: Common.Payback_BankStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOwnershipManager"
  ): TypedContractMethod<[newManager: AddressLike], [boolean], "nonpayable">;

  filters: {};
}
