/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetClass,
  IAssetClassInterface,
} from "../../../contracts/apis/IAssetClass";

const _abi = [
  {
    inputs: [],
    name: "Locked",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "UnSupportedAsset",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
    ],
    name: "isSupportedAsset",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAssetClass__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetClassInterface {
    return new Interface(_abi) as IAssetClassInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAssetClass {
    return new Contract(address, _abi, runner) as unknown as IAssetClass;
  }
}
