/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFactory,
  IFactoryInterface,
} from "../../../contracts/apis/IFactory";

const _abi = [
  {
    inputs: [],
    name: "AllMemberIsPaid",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint24",
        name: "ccr",
        type: "uint24",
      },
    ],
    name: "CollateralCoverageCannotGoBelow_100",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientFund",
    type: "error",
  },
  {
    inputs: [],
    name: "OwnershipManagerIsNotSet",
    type: "error",
  },
  {
    inputs: [],
    name: "QuorumIsInvalid",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "_value",
                    type: "uint256",
                  },
                ],
                internalType: "struct Counters.Counter",
                name: "userCount",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unitId",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "rId",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "bank",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "durOfChoice",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "expInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "payDate",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "turnTime",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "loan",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colBals",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "id",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "sentQuota",
                    type: "bool",
                  },
                ],
                internalType: "struct Common.Contributor[]",
                name: "cData",
                type: "tuple[]",
              },
              {
                internalType: "enum Common.Router",
                name: "router",
                type: "uint8",
              },
              {
                internalType: "enum Common.FuncTag",
                name: "stage",
                type: "uint8",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
              {
                internalType: "bool",
                name: "sentQuota",
                type: "bool",
              },
            ],
            internalType: "struct Common.Contributor",
            name: "cData",
            type: "tuple",
          },
        ],
        indexed: false,
        internalType: "struct Common.CreatePoolReturnValue",
        name: "",
        type: "tuple",
      },
    ],
    name: "BandCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "Cancellation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "_value",
                    type: "uint256",
                  },
                ],
                internalType: "struct Counters.Counter",
                name: "userCount",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unitId",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "rId",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "bank",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "durOfChoice",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "expInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "payDate",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "turnTime",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "loan",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colBals",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "id",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "sentQuota",
                    type: "bool",
                  },
                ],
                internalType: "struct Common.Contributor[]",
                name: "cData",
                type: "tuple[]",
              },
              {
                internalType: "enum Common.Router",
                name: "router",
                type: "uint8",
              },
              {
                internalType: "enum Common.FuncTag",
                name: "stage",
                type: "uint8",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "debtBal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "colBal",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "GetFinanced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "_value",
                    type: "uint256",
                  },
                ],
                internalType: "struct Counters.Counter",
                name: "userCount",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unitId",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "rId",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "bank",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "durOfChoice",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "expInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "payDate",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "turnTime",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "loan",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colBals",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "id",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "sentQuota",
                    type: "bool",
                  },
                ],
                internalType: "struct Common.Contributor[]",
                name: "cData",
                type: "tuple[]",
              },
              {
                internalType: "enum Common.Router",
                name: "router",
                type: "uint8",
              },
              {
                internalType: "enum Common.FuncTag",
                name: "stage",
                type: "uint8",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "debtBal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "colBal",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "Liquidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "_value",
                    type: "uint256",
                  },
                ],
                internalType: "struct Counters.Counter",
                name: "userCount",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unitId",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "rId",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "bank",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "durOfChoice",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "expInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "payDate",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "turnTime",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "loan",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colBals",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "id",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "sentQuota",
                    type: "bool",
                  },
                ],
                internalType: "struct Common.Contributor[]",
                name: "cData",
                type: "tuple[]",
              },
              {
                internalType: "enum Common.Router",
                name: "router",
                type: "uint8",
              },
              {
                internalType: "enum Common.FuncTag",
                name: "stage",
                type: "uint8",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "debtBal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "colBal",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "NewMemberAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "_value",
                    type: "uint256",
                  },
                ],
                internalType: "struct Counters.Counter",
                name: "userCount",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unitId",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "rId",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "bank",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "durOfChoice",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "expInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "payDate",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "turnTime",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "loan",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colBals",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "id",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "sentQuota",
                    type: "bool",
                  },
                ],
                internalType: "struct Common.Contributor[]",
                name: "cData",
                type: "tuple[]",
              },
              {
                internalType: "enum Common.Router",
                name: "router",
                type: "uint8",
              },
              {
                internalType: "enum Common.FuncTag",
                name: "stage",
                type: "uint8",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "debtBal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "colBal",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "Payback",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "Rekeyed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "userCount",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "quorum",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "selector",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colCoverage",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "duration",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intRate",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uints",
            name: "uints",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "fullInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intPerSec",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "unit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "currentPool",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "unitId",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "rId",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uint256s",
            name: "uint256s",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "address",
                name: "lastPaid",
                type: "address",
              },
              {
                internalType: "address",
                name: "bank",
                type: "address",
              },
              {
                internalType: "address",
                name: "admin",
                type: "address",
              },
            ],
            internalType: "struct Common.Addresses",
            name: "addrs",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "allGh",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
              {
                internalType: "bool",
                name: "sentQuota",
                type: "bool",
              },
            ],
            internalType: "struct Common.Contributor[]",
            name: "cData",
            type: "tuple[]",
          },
          {
            internalType: "enum Common.Router",
            name: "router",
            type: "uint8",
          },
          {
            internalType: "enum Common.FuncTag",
            name: "stage",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType: "struct Common.Pool",
        name: "",
        type: "tuple",
      },
    ],
    name: "RoundUp",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "intRate",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "durationInHours",
        type: "uint16",
      },
      {
        internalType: "uint24",
        name: "colCoverage",
        type: "uint24",
      },
      {
        internalType: "uint256",
        name: "unitLiquidity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "liquidAsset",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "contributors",
        type: "address[]",
      },
    ],
    name: "createPermissionedPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "intRate",
        type: "uint16",
      },
      {
        internalType: "uint8",
        name: "quorum",
        type: "uint8",
      },
      {
        internalType: "uint16",
        name: "durationInHours",
        type: "uint16",
      },
      {
        internalType: "uint24",
        name: "colCoverage",
        type: "uint24",
      },
      {
        internalType: "uint256",
        name: "unitLiquidity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "liquidAsset",
        type: "address",
      },
    ],
    name: "createPermissionlessPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "enquireLiquidation",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "durOfChoice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expInterest",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "payDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "turnTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "loan",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "colBals",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "id",
            type: "address",
          },
          {
            internalType: "bool",
            name: "sentQuota",
            type: "bool",
          },
        ],
        internalType: "struct Common.Contributor",
        name: "_liq",
        type: "tuple",
      },
      {
        internalType: "bool",
        name: "defaulted",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "currentDebt",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isMember",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isAdmin",
            type: "bool",
          },
        ],
        internalType: "struct Common.Slot",
        name: "slot",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "getBalances",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "xfi",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "erc20",
            type: "uint256",
          },
        ],
        internalType: "struct Common.Balances",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "getCurrentDebt",
    outputs: [
      {
        internalType: "uint256",
        name: "debtToDate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getEpoches",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "daysOfUseInHr",
        type: "uint8",
      },
    ],
    name: "getFinance",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getPoint",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "contributor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "creator",
            type: "uint256",
          },
        ],
        internalType: "struct Common.Point",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unitId",
        type: "uint256",
      },
    ],
    name: "getPoolData",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "userCount",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "quorum",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "selector",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colCoverage",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "duration",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intRate",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uints",
            name: "uints",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "fullInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intPerSec",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "unit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "currentPool",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "unitId",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "rId",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uint256s",
            name: "uint256s",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "address",
                name: "lastPaid",
                type: "address",
              },
              {
                internalType: "address",
                name: "bank",
                type: "address",
              },
              {
                internalType: "address",
                name: "admin",
                type: "address",
              },
            ],
            internalType: "struct Common.Addresses",
            name: "addrs",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "allGh",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
              {
                internalType: "bool",
                name: "sentQuota",
                type: "bool",
              },
            ],
            internalType: "struct Common.Contributor[]",
            name: "cData",
            type: "tuple[]",
          },
          {
            internalType: "enum Common.Router",
            name: "router",
            type: "uint8",
          },
          {
            internalType: "enum Common.FuncTag",
            name: "stage",
            type: "uint8",
          },
        ],
        internalType: "struct Common.Pool",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getProfile",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "durOfChoice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expInterest",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "payDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "turnTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "loan",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "colBals",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "id",
            type: "address",
          },
          {
            internalType: "bool",
            name: "sentQuota",
            type: "bool",
          },
        ],
        internalType: "struct Common.Contributor",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRecordEpoches",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "getSlot",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isMember",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isAdmin",
            type: "bool",
          },
        ],
        internalType: "struct Common.Slot",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "getStatus",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isInitialized",
            type: "bool",
          },
          {
            internalType: "enum Common.Status",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct Common.Unit",
        name: "_unit",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "joinAPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "liquidate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "payback",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unit",
        type: "uint256",
      },
    ],
    name: "removeLiquidityPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryInterface {
    return new Interface(_abi) as IFactoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFactory {
    return new Contract(address, _abi, runner) as unknown as IFactory;
  }
}
