/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISmartStrategyAdmin,
  ISmartStrategyAdminInterface,
} from "../../../contracts/apis/ISmartStrategyAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "InsufficientMsgValue",
    type: "error",
  },
  {
    inputs: [],
    name: "NoStrategyFound",
    type: "error",
  },
  {
    inputs: [],
    name: "OperationFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "RouterNotSet",
    type: "error",
  },
  {
    inputs: [],
    name: "StatusAlreadyUpdated",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "StrategyWasDeleted",
    type: "error",
  },
  {
    inputs: [],
    name: "UpgradeNotReady",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "createStrategy",
    outputs: [
      {
        internalType: "address",
        name: "strategy",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
    ],
    name: "rekeyStrategy",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISmartStrategyAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): ISmartStrategyAdminInterface {
    return new Interface(_abi) as ISmartStrategyAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISmartStrategyAdmin {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISmartStrategyAdmin;
  }
}
