/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStrategyManager,
  IStrategyManagerInterface,
} from "../../../contracts/apis/IStrategyManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "createStrategy",
    outputs: [
      {
        internalType: "address",
        name: "strategy",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStrategyManager__factory {
  static readonly abi = _abi;
  static createInterface(): IStrategyManagerInterface {
    return new Interface(_abi) as IStrategyManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStrategyManager {
    return new Contract(address, _abi, runner) as unknown as IStrategyManager;
  }
}
