/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISupportedAsset,
  ISupportedAssetInterface,
} from "../../../contracts/apis/ISupportedAsset";

const _abi = [
  {
    inputs: [],
    name: "getDefaultSupportedCollateralAsset",
    outputs: [
      {
        internalType: "address",
        name: "_default",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
    ],
    name: "isSupportedAsset",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISupportedAsset__factory {
  static readonly abi = _abi;
  static createInterface(): ISupportedAssetInterface {
    return new Interface(_abi) as ISupportedAssetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISupportedAsset {
    return new Contract(address, _abi, runner) as unknown as ISupportedAsset;
  }
}
