/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AbstractFactory,
  AbstractFactoryInterface,
} from "../../../contracts/abstracts/AbstractFactory";

const _abi = [
  {
    inputs: [],
    name: "AllMemberIsPaid",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint24",
        name: "ccr",
        type: "uint24",
      },
    ],
    name: "CollateralCoverageCannotGoBelow_100",
    type: "error",
  },
  {
    inputs: [],
    name: "EnforcedPause",
    type: "error",
  },
  {
    inputs: [],
    name: "ExpectedPause",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "enum Common.FuncTag",
        name: "",
        type: "uint8",
      },
    ],
    name: "FunctionAlreadyLocked",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "enum Common.FuncTag",
        name: "",
        type: "uint8",
      },
    ],
    name: "FunctionAlreadyUnlocked",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    name: "FunctionNotCallable",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "IndexOutOfBound",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientFund",
    type: "error",
  },
  {
    inputs: [],
    name: "OwnershipManagerIsNotSet",
    type: "error",
  },
  {
    inputs: [],
    name: "QuorumIsInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "ReentrancyGuardReentrantCall",
    type: "error",
  },
  {
    inputs: [],
    name: "UpdateStrategyError",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "strategy",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "isPermissionless",
                type: "bool",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
            ],
            internalType: "struct Common.Contributor",
            name: "contributor",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "epochId",
            type: "uint256",
          },
          {
            internalType: "uint16",
            name: "spot",
            type: "uint16",
          },
        ],
        indexed: false,
        internalType: "struct Common.CreatePoolReturnValue",
        name: "",
        type: "tuple",
      },
    ],
    name: "BandCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "Cancellation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "slot",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "bool",
                name: "admin",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "member",
                type: "bool",
              },
            ],
            internalType: "struct Common.Rank",
            name: "rank",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
            ],
            internalType: "struct Common.Contributor",
            name: "cbData",
            type: "tuple",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "strategy",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "isPermissionless",
                type: "bool",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "GetFinanced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "slot",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "bool",
                name: "admin",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "member",
                type: "bool",
              },
            ],
            internalType: "struct Common.Rank",
            name: "rank",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
            ],
            internalType: "struct Common.Contributor",
            name: "cbData",
            type: "tuple",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "strategy",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "isPermissionless",
                type: "bool",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "Liquidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "slot",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "bool",
                name: "admin",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "member",
                type: "bool",
              },
            ],
            internalType: "struct Common.Rank",
            name: "rank",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
            ],
            internalType: "struct Common.Contributor",
            name: "cbData",
            type: "tuple",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "strategy",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "isPermissionless",
                type: "bool",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "NewMemberAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "slot",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "bool",
                name: "admin",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "member",
                type: "bool",
              },
            ],
            internalType: "struct Common.Rank",
            name: "rank",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
            ],
            internalType: "struct Common.Contributor",
            name: "cbData",
            type: "tuple",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "quorum",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "selector",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "colCoverage",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "duration",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uints",
                name: "uints",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "fullInterest",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "intPerSec",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "unit",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "currentPool",
                    type: "uint256",
                  },
                ],
                internalType: "struct Common.Uint256s",
                name: "uint256s",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "asset",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "lastPaid",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "strategy",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "admin",
                    type: "address",
                  },
                ],
                internalType: "struct Common.Addresses",
                name: "addrs",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "allGh",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "isPermissionless",
                type: "bool",
              },
            ],
            internalType: "struct Common.Pool",
            name: "pool",
            type: "tuple",
          },
        ],
        indexed: false,
        internalType: "struct Common.CommonEventData",
        name: "",
        type: "tuple",
      },
    ],
    name: "Payback",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "Rekeyed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "quorum",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "selector",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colCoverage",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "duration",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intRate",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uints",
            name: "uints",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "fullInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intPerSec",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "unit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "currentPool",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uint256s",
            name: "uint256s",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "address",
                name: "lastPaid",
                type: "address",
              },
              {
                internalType: "address",
                name: "strategy",
                type: "address",
              },
              {
                internalType: "address",
                name: "admin",
                type: "address",
              },
            ],
            internalType: "struct Common.Addresses",
            name: "addrs",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "allGh",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isPermissionless",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct Common.Pool",
        name: "",
        type: "tuple",
      },
    ],
    name: "RoundUp",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "intRate",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "durationInHours",
        type: "uint16",
      },
      {
        internalType: "uint24",
        name: "colCoverage",
        type: "uint24",
      },
      {
        internalType: "uint256",
        name: "unitLiquidity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "liquidAsset",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "contributors",
        type: "address[]",
      },
    ],
    name: "createPermissionedPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "intRate",
        type: "uint16",
      },
      {
        internalType: "uint8",
        name: "quorum",
        type: "uint8",
      },
      {
        internalType: "uint16",
        name: "durationInHours",
        type: "uint16",
      },
      {
        internalType: "uint24",
        name: "colCoverage",
        type: "uint24",
      },
      {
        internalType: "uint256",
        name: "unitLiquidity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "liquidAsset",
        type: "address",
      },
    ],
    name: "createPermissionlessPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "creationFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "enquireLiquidation",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "durOfChoice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expInterest",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "payDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "turnTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "loan",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "colBals",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "id",
            type: "address",
          },
        ],
        internalType: "struct Common.Contributor",
        name: "",
        type: "tuple",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "epoches",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "getBalances",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "xfi",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "erc20",
            type: "uint256",
          },
        ],
        internalType: "struct Common.Balances",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "getCollaterlQuote",
    outputs: [
      {
        internalType: "uint256",
        name: "collateral",
        type: "uint256",
      },
      {
        internalType: "uint24",
        name: "colCoverage",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getContractData",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "feeTo",
            type: "address",
          },
          {
            internalType: "address",
            name: "assetAdmin",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "makerRate",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "strategyManager",
            type: "address",
          },
        ],
        internalType: "struct IFactory.ContractData",
        name: "result",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "getCurrentDebt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "daysOfUseInHr",
        type: "uint8",
      },
    ],
    name: "getFinance",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "getPoolData",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "quorum",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "selector",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colCoverage",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "duration",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intRate",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uints",
            name: "uints",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "fullInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intPerSec",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "unit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "currentPool",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uint256s",
            name: "uint256s",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "address",
                name: "lastPaid",
                type: "address",
              },
              {
                internalType: "address",
                name: "strategy",
                type: "address",
              },
              {
                internalType: "address",
                name: "admin",
                type: "address",
              },
            ],
            internalType: "struct Common.Addresses",
            name: "addrs",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "allGh",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isPermissionless",
            type: "bool",
          },
        ],
        internalType: "struct Common.Pool",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolFromAllEpoches",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "quorum",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "selector",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colCoverage",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "duration",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intRate",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uints",
            name: "uints",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "fullInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "intPerSec",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "unit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "currentPool",
                type: "uint256",
              },
            ],
            internalType: "struct Common.Uint256s",
            name: "uint256s",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "address",
                name: "lastPaid",
                type: "address",
              },
              {
                internalType: "address",
                name: "strategy",
                type: "address",
              },
              {
                internalType: "address",
                name: "admin",
                type: "address",
              },
            ],
            internalType: "struct Common.Addresses",
            name: "addrs",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "allGh",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isPermissionless",
            type: "bool",
          },
        ],
        internalType: "struct Common.Pool[]",
        name: "pools",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getProfile",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "durOfChoice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expInterest",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "payDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "turnTime",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "loan",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "colBals",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "id",
                type: "address",
              },
            ],
            internalType: "struct Common.Contributor",
            name: "cData",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "bool",
                name: "admin",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "member",
                type: "bool",
              },
            ],
            internalType: "struct Common.Rank",
            name: "rank",
            type: "tuple",
          },
          {
            internalType: "uint8",
            name: "slot",
            type: "uint8",
          },
        ],
        internalType: "struct Common.ContributorData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "functionSelector",
        type: "uint8",
      },
    ],
    name: "isFunctionCallable",
    outputs: [
      {
        internalType: "string",
        name: "_isCallable",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "joinAPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "liquidate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "minContribution",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ownershipManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "payback",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "serviceRate",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "_minContribution",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "setUpFee",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "feeTo",
        type: "address",
      },
      {
        internalType: "address",
        name: "assetClass",
        type: "address",
      },
      {
        internalType: "address",
        name: "strategyManager",
        type: "address",
      },
    ],
    name: "performSetUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "permits",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "removeLiquidityPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "feeTo",
        type: "address",
      },
      {
        internalType: "address",
        name: "assetAdmin",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "serviceRate",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "_creationFee",
        type: "uint256",
      },
    ],
    name: "setContractData",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minLiquidity",
        type: "uint256",
      },
    ],
    name: "setMinimumLiquidityPerProvider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newManager",
        type: "address",
      },
    ],
    name: "setOwnershipManager",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
    ],
    name: "withdrawCollateral",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "withdrawXFI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class AbstractFactory__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractFactoryInterface {
    return new Interface(_abi) as AbstractFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AbstractFactory {
    return new Contract(address, _abi, runner) as unknown as AbstractFactory;
  }
}
