/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  CallContext,
  CallContextInterface,
} from "../../../../contracts/implementations/token/CallContext";

const _abi = [
  {
    inputs: [],
    name: "FunctionNotCallable",
    type: "error",
  },
] as const;

export class CallContext__factory {
  static readonly abi = _abi;
  static createInterface(): CallContextInterface {
    return new Interface(_abi) as CallContextInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): CallContext {
    return new Contract(address, _abi, runner) as unknown as CallContext;
  }
}
