/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIAOracleV2__factory } from "./DIAOracleV2__factory";
export { IDIAOracleV2__factory } from "./IDIAOracleV2__factory";
